sudo: required

language: minimal

services: docker

install:
    - docker-compose build

before_script:
    - docker-compose up -d app

script:
    - docker-compose run app ./project-tests.sh
    - ./.docker/smoke-tests.sh

after_script:
    - docker-compose down
