sudo: required

language: minimal

services: docker

install:
    - docker-compose build

script:
    - docker-compose run web python -m pytest
    - docker-compose up -d web
    - ./smoke_tests.sh

after_script:
    - docker-compose down
