ARG python_base_image_tag
FROM python:${python_base_image_tag}
RUN pip install --no-cache-dir --only-binary --upgrade pipenv

RUN apk --no-cache add linux-headers g++

COPY Pipfile Pipfile.lock ./

ARG pipenv_dev_arg
ENV PIPENV_VENV_IN_PROJECT=1 
RUN pipenv install ${pipenv_dev_arg} --deploy --ignore-pipfile
