ARG python_base_image_tag
FROM python:${python_base_image_tag}

# uwsgi build process dependencies
RUN apk update && apk add gcc libc-dev linux-headers
RUN pip install --no-cache-dir --only-binary --upgrade pipenv

COPY Pipfile Pipfile.lock ./

ARG pipenv_dev_arg
ENV PIPENV_VENV_IN_PROJECT=1 
RUN pipenv install ${pipenv_dev_arg} --deploy --ignore-pipfile
