ARG python_base_image_tag
FROM python:${python_base_image_tag}

# uwsgi build process dependencies
RUN apk add --no-cache gcc libc-dev linux-headers
RUN pip install --no-cache-dir --only-binary --upgrade pipenv

RUN python -m venv /.venv
ENV VIRTUAL_ENV=/.venv PYTHONUSERBASE=/.venv PATH=/.venv/bin:$PATH
COPY Pipfile Pipfile.lock /pipfiles/

ARG pipenv_dev_arg
WORKDIR /pipfiles
RUN pipenv install ${pipenv_dev_arg} --deploy --ignore-pipfile
